const mockData = [
  {
    id: 1,
    name: "John Doe",
    fatherName: "Michael Doe",
    gender: "Male",
    number: "1234567890",
    trade: "Game Development",
  },
  {
    id: 2,
    name: "Jane Smith",
    fatherName: "Robert Smith",
    gender: "Female",
    number: "0987654321",
    trade: "PMP",
  },
  {
    id: 3,
    name: "Alice Johnson",
    fatherName: "David Johnson",
    gender: "Female",
    number: "1122334455",
    trade: "Digital Marketing",
  },
  {
    id: 4,
    name: "Bob Williams",
    fatherName: "James Williams",
    gender: "Male",
    number: "5566778899",
    trade: "MERN",
  },
  {
    id: 5,
    name: "Charlie Brown",
    fatherName: "Henry Brown",
    gender: "Male",
    number: "6677889900",
    trade: "AWS",
  },
  {
    id: 6,
    name: "Diana Miller",
    fatherName: "Paul Miller",
    gender: "Female",
    number: "7788990011",
    trade: "App Development",
  },
  {
    id: 7,
    name: "Edward Wilson",
    fatherName: "Mark Wilson",
    gender: "Male",
    number: "8899001122",
    trade: "PMP",
  },
  {
    id: 8,
    name: "Fiona Davis",
    fatherName: "Peter Davis",
    gender: "Female",
    number: "9900112233",
    trade: "Game Development",
  },
  {
    id: 9,
    name: "George Clark",
    fatherName: "Samuel Clark",
    gender: "Male",
    number: "1011121314",
    trade: "Digital Marketing",
  },
  {
    id: 10,
    name: "Hannah Lewis",
    fatherName: "Benjamin Lewis",
    gender: "Female",
    number: "1213141516",
    trade: "MERN",
  },
  {
    id: 11,
    name: "Isaac Walker",
    fatherName: "William Walker",
    gender: "Male",
    number: "1415161718",
    trade: "AWS",
  },
  {
    id: 12,
    name: "Jessica Hall",
    fatherName: "Arthur Hall",
    gender: "Female",
    number: "1516171819",
    trade: "App Development",
  },
  {
    id: 13,
    name: "Kevin Allen",
    fatherName: "Thomas Allen",
    gender: "Male",
    number: "1617181920",
    trade: "PMP",
  },
  {
    id: 14,
    name: "Laura Young",
    fatherName: "Richard Young",
    gender: "Female",
    number: "1718192021",
    trade: "Game Development",
  },
  {
    id: 15,
    name: "Michael King",
    fatherName: "Daniel King",
    gender: "Male",
    number: "1819202122",
    trade: "Digital Marketing",
  },
  {
    id: 16,
    name: "Natalie Wright",
    fatherName: "Anthony Wright",
    gender: "Female",
    number: "1920212223",
    trade: "MERN",
  },
  {
    id: 17,
    name: "Oliver Scott",
    fatherName: "Patrick Scott",
    gender: "Male",
    number: "2021222324",
    trade: "AWS",
  },
  {
    id: 18,
    name: "Penelope Baker",
    fatherName: "Stephen Baker",
    gender: "Female",
    number: "2122232425",
    trade: "App Development",
  },
  {
    id: 19,
    name: "Quentin Green",
    fatherName: "Jonathan Green",
    gender: "Male",
    number: "2223242526",
    trade: "PMP",
  },
  {
    id: 20,
    name: "Rachel Adams",
    fatherName: "Charles Adams",
    gender: "Female",
    number: "2324252627",
    trade: "Game Development",
  },
];

export default mockData;
